### PR TITLE
SOLDER-93

### PR DESCRIPTION
**Pull request by jharting**

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
I am getting test failures after this commit:

Failed tests: 
  testBeanAvailable(org.jboss.seam.solder.test.core.requires.ReturnTypeDependencyUnavailableTest)
  testBeanAvailable(org.jboss.seam.solder.test.core.requires.SupertypeDependencyUnavailableTest)
  testBeanUnavailable(org.jboss.seam.solder.test.core.requires.NoDependencyBeanAvailableTest)

Tests in error: 
  org.jboss.seam.solder.test.core.requires.FieldDependencyUnavailableTest
  testUnavailabilityOfBeans(org.jboss.seam.solder.test.core.requires.PackageLevelDependencyUnavailableTest)
  org.jboss.seam.solder.test.core.CoreTest

**Comment by jharting** [comment]
I am getting a clean run on JBoss AS 6.0.0.Final

**Comment by jharting** [comment]
I see the problem. The failures only happen in a weld-embedded.

**Comment by jharting** [comment]
Looks like I cannot control the classpath by bundling specific classes in a deployed artifact in the embedded mode. This is quite crucial for the tests to work properly.

**Comment by stuartwdouglas** [comment]
It may be possible to accomplish this using the maven shade plugins 'relocations' feature, to rename classes that were present during compilation into classes that do not exist. 

Byteman may be another option, as you could use it to instrument the CL so it always fails to load certain classes.

**Comment by jharting** [comment]
I have rewritten the tests and used a static initializer hack for a class not to get loaded in the embedded mode (https://github.com/jharting/seam-solder/blob/253bbd90183176ae064ae402274805c9b2b0f5d5/impl/src/test/java/org/jboss/seam/solder/test/core/requires/Jaguar.java)

Please review again.

**Pull request merged**
