### PR TITLE
Add ability to get only writable properties from PropertyQuery

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by pmuir** [comment]
Only thought I have, would the API look better like:

List<Property<?>> getResultList(boolean writable);

With the getResultList() method specifying false by default?

**Comment by stuartwdouglas** [comment]
I considered that, but you still end up with two methods, and I think generally you will only be interested in one or the other, (i.e. it will always be getResultList(true) or getResultList(false) not getResultList(someFlag)).

In this case I think getWritableResultList() is a lot clearer when reading than getResultList(true)

**Comment by pmuir** [comment]
Yeah, I'm on the fence here. getWritableResultList() is not nice to read, otoh this is what the javabean spec calls it, so I think we are good. Will merge.

**Comment by stuartwdouglas** [comment]
merged

**Pull request merged**
