### PR TITLE
Move LogManager usage into try/catch, on GAE LogManager is restricted cla

### PR DESCRIPTION
**Pull request by alesj**
Move LogManager usage into try/catch, on GAE LogManager is restricted class

### CODE REVIEW

**Comment by mojavelinux** [comment]
This is being tracked upstream in JBoss Logging: https://issues.jboss.org/browse/JBLOGGING-47

**Comment by LightGuard** [comment]
Do we need to merge this in?

**Comment by alesj** [comment]
I think we need to re-evaluate why (or how) is logging bundled with Solder.
It should at least be properly (with package "offset") jarjar-ed, not to overlap with original.

**Comment by lincolnthree** [comment]
Closing as out of date. Please re-open with new pull request if still relevant.

**Pull request closed without merging**
