### PR TITLE
SOLDER-153 handledException in conversation scope

### PR DESCRIPTION
**Pull request by blabno**
ExceptionHandlerDispatch is invalid, cause it's in dependant scope so when it sets exceptionToCatch or exceptionStack it's different instance then when @Produces method for handledException is called which always results in null.

### CODE REVIEW

**Comment by LightGuard** [comment]
This will cause a problem for exceptions that are passed from a servlet, JAX-RS etc. anywhere we're a conversation isn't available. Perhaps request scope makes more sense?

**Comment by blabno** [comment]
Jason, as in Seam2 users will do redirects to some error page so we need to survive redirect. Request scope is not enough.

**Comment by LightGuard** [comment]
But Catch is for more than just JSF.

IIRC, we talked about this during the design and the idea was if you wanted
to make use of it in a conversation route, you'd redefine the producer to
be conversation scoped if your application. You could either create a new
one, or modify it with Seam Config.

On Mon, Feb 6, 2012 at 12:24, Bernard Labno <
reply@reply.github.com

> wrote:
> 
> Jason, as in Seam2 users will do redirects to some error page so we need
> to survive redirect. Request scope is not enough.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/seam/solder/pull/74#issuecomment-3834927

## 

Jason Porter
http://lightguard-jp.blogspot.com
http://twitter.com/lightguardjp

Software Engineer
Open Source Advocate
Author of Seam Catch - Next Generation Java Exception Handling

PGP key id: 926CCFF5
PGP key available at: keyserver.net, pgp.mit.edu

**Comment by blabno** [comment]
AH, ok, so le's remove first commit that adds @ConversationScoped annotation to the entire component but the second commit is a must.

**Comment by LightGuard** [comment]
Sure, that works. Do you want to update the pull request or should I just cherry pick it?

**Comment by blabno** [comment]
I'll add additional commit.

**Pull request merged**
