### PR TITLE
ServiceHandlerExtension - organized code

### PR DESCRIPTION
**Pull request by walterjwhite**
Hi Pete,

I cleaned up the ServiceHandlerExtension.java with a few comments and put functionality into separate methods so that this class may be sub-classed.

I can format the code with spaces if needed.

Let me know what you think,

Walter

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
This needs to follow our style guidelines (see http://sfwk.org/Seam3/DevelopmentGuidelines, there is an eclipse code formatter profile). 

Also for a minor change like this you should rebase it down to one commit to make it easier to see exactly what you have changed (git rebase -i master).

**Comment by walterjwhite** [comment]
Stuart,

Thanks for your comments, I will update the code to follow the style guidelines and rebase it down to a single commit.

Walter

**Comment by walterjwhite** [comment]
Stuart,

I closed the other request (opened by accident).  I believe I rebased and squashed everything into a single commit, but I still see 13 commits.

Let me know if I still need to rebase and if you can help me with that.

Thanks,

Walter

**Comment by stuartwdouglas** [comment]
To rebase run git rebase -i origin/master 

an editor will then open, and you can change the 'pick' next to your commit to 's' (for squash)

This will allow you to squash all the commits into one.

**Comment by walterjwhite** [comment]
Stuart,

Thanks, I learned something new - Also, just so you're aware too (probably are), but if you already push your commits, you cannot rebase them on github.  That explains why I couldn't 'squash' my commits.  I created a new repository and merged my changes in there in a single commit.

Hopefully that helps.

Walter

**Comment by mojavelinux** [comment]
Thanks Walter. We'll get this integrated before the upcoming release.

**Comment by walterjwhite** [comment]
Cool - Thanks for getting back to me.

**Comment by mojavelinux** [comment]
I've merged in these changes, but because of conflicts, it didn't associate it properly to your commit, so it looks like I committed it. On the other hand, your name is in the @author tag :)

**Pull request closed without merging**
